
DROP TABLE nhincuser.aa_to_home_community_mapping;
DROP TABLE nhincuser.auditrepository;
DROP TABLE nhincuser.document;
DROP TABLE nhincuser.eventcode;
DROP TABLE nhincuser.correlatedidentifiers;
DROP TABLE nhincuser.subscription;
DROP TABLE nhincuser.asyncmsgrepo;
DROP TABLE nhincuser.gateway_lift_message;
DROP TABLE nhincuser.transfer_data;
DROP TABLE nhincuser.patient;
DROP TABLE nhincuser.identifier;
DROP TABLE nhincuser.personname;
DROP TABLE nhincuser.address;
DROP TABLE nhincuser.phonenumber;
DROP TABLE nhincuser.pddeferredcorrelation;
DROP TABLE nhincuser.log;
DROP TABLE nhincuser.transactionrepository;
DROP TABLE nhincuser.event;
DROP TABLE nhincuser.ADVANCED_AUDIT;
DROP TABLE nhincuser.ANCHOR;
DROP TABLE nhincuser.CERTIFICATE;
DROP TABLE nhincuser.CERTPOLICYGROUPDOMAINRELTN;
DROP TABLE nhincuser.CERTPOLICYGROUPRELTN;
DROP TABLE nhincuser.CERTPOLICYGROUP;
DROP TABLE nhincuser.CERTPOLICY;
DROP TABLE nhincuser.DNSRECORD;
DROP TABLE nhincuser.MONITOREDMESSAGENOTIFICATION;
DROP TABLE nhincuser.MONITOREDMESSAGE;
DROP TABLE nhincuser.PAGEPREFERENCE;
DROP TABLE nhincuser.SETTING;
DROP TABLE nhincuser.TRUSTBUNDLEDOMAINRELTN;
DROP TABLE nhincuser.TRUSTBUNDLEANCHOR;
DROP TABLE nhincuser.TRUSTBUNDLE;
DROP TABLE nhincuser.USERLOGIN;
DROP TABLE nhincuser.USERROLE;
DROP TABLE nhincuser.CONFIG_ADDRESS;
DROP TABLE nhincuser.DOMAIN;
DROP SEQUENCE nhincuser.hibernate_sequence;

DROP USER nhincuser;

COMMIT;
